#!bin/bash

# I know there has to be a better way to do this, but
# this is just a temporary solution until I figure that
# out.
echo "Renaming..."
# make capital letters lowercase
find -name "*" -type d | rename "y/A-Z/a-z/"; find -name "*" -type f | rename "y/A-Z/a-z/"
# space
find -name "* *" -type d | rename "s/ /-/g"
find -name "* *" -type f | rename "s/ /-/g"
# _
find -name "*_*" -type d | rename "s/_/-/g"
find -name "*_*" -type f | rename "s/_/-/g"
# (
find -name "*(*" -type d | rename "s/\(//g"
find -name "*(*" -type f | rename "s/\(//g"
# )
find -name "*)*" -type d | rename "s/\)//g"
find -name "*)*" -type f | rename "s/\)//g"
# '
find -name "*'*" -type d | rename "s/\'//g"
find -name "*'*" -type f | rename "s/\'//g"
# ,
find -name "*,*" -type d | rename "s/,//g"
find -name "*,*" -type f | rename "s/,//g"
# ?
find -name "*?*" -type d | rename "s/\?//g"
find -name "*?*" -type f | rename "s/\?//g"
# [
find -name "*[*" -type d | rename "s/\[//g"
find -name "*[*" -type f | rename "s/\[//g"
# ]
find -name "*]*" -type d | rename "s/\]//g"
find -name "*]*" -type f | rename "s/\]//g"
# "
find -name '*"*' -type d | rename 's/\"//g'
find -name '*"*' -type f | rename 's/\"//g'
# %
find -name "*%*" -type d | rename "s/\%//g"
find -name "*%*" -type f | rename "s/\%//g"
# $
find -name "*\$*" -type d | rename "s/\$//g"
find -name "*\$*" -type f | rename "s/\$//g"
# &
find -name "*&*" -type d | rename "s/\&//g"
find -name "*&*" -type f | rename "s/\&//g"
# !
find -name "*!*" -type d | rename "s/\!//g"
find -name "*!*" -type f | rename "s/\!//g"
# @
find -name "*@*" -type d | rename "s/@//g"
find -name "*@*" -type f | rename "s/@//g"
# ^
find -name "*^*" -type d | rename "s/\^//g"
find -name "*^*" -type f | rename "s/\^//g"
# #
find -name "*#*" -type d | rename "s/#//g"
find -name "*#*" -type f | rename "s/#//g"

echo "Finished."
